using System.Diagnostics;
using System.Text.Json.Nodes;

internal static class CodeFixTests
{
	internal static TestGroup Build(TestContext ctx)
	{
		async Task<(bool ok, JsonNode? data, string text)> Call(string tool, object args)
		{
			await ctx.SendAsync(new { jsonrpc = "2.0", id = ctx.NextId(), method = "tools/call",
				@params = new { name = tool, arguments = args } });
			
			var resp = await ctx.ReceiveAsync();
			var text = resp?["result"]?["content"]?[0]?["text"]?.GetValue<string>() ?? string.Empty;
			
			JsonNode? data = null;
			
			try { data = JsonNode.Parse(text); }
			catch { }
			
			return (resp?["error"] is null && text.Length > 0, data, text);
		}
		
		async Task<(bool pass, string msg)> RunApplyNintFix()
		{
			var fixturePath = Path.Combine(ctx.RepoRoot, "src", "RoslynMcp", "_CodeFixFixture_.cs");
			var sw = Stopwatch.StartNew();
			
			try {
				
				await File.WriteAllTextAsync(fixturePath, """
					// AUTO-GENERATED by TestHarness — safe to delete.
					using System;
					
					namespace RoslynMcp;
					
					class _CodeFixFixture_
					{
						IntPtr handle;
					}
					""");
				
				await Task.Delay(600);
				
				var (_, pvData, pvText) = await Call("roslyn_preview_code_fix", new {
					projectPath = ctx.TargetPath,
					filePath = "_CodeFixFixture_.cs",
					line = 8,
					column = 3,
					diagnosticId = "RMCP001"
				});
				
				var token = pvData?["token"]?.GetValue<string>();
				var diff = pvData?["diff"]?.GetValue<string>() ?? string.Empty;
				
				if(token is null || !diff.Contains("nint", StringComparison.Ordinal))
					return (false, $"FAIL  (preview missing token/diff: {pvText}) [{sw.ElapsedMilliseconds}ms]");
				
				var (_, apData, apText) = await Call("roslyn_apply_code_fix", new {
					token,
					approval = "y",
					projectPath = ctx.TargetPath
				});
				
				var error = apData?["error"]?.GetValue<string>();
				var filesWritten = apData?["filesWritten"]?.GetValue<int>();
				var updated = await File.ReadAllTextAsync(fixturePath);
				var pass = error is null && filesWritten >= 1 && updated.Contains("nint handle", StringComparison.Ordinal);
				
				return (pass,
					pass
						? $"PASS  [{sw.ElapsedMilliseconds}ms]"
						: $"FAIL  (apply: {apText}) [{sw.ElapsedMilliseconds}ms]");
			}
			finally {
				
				if(File.Exists(fixturePath))
					File.Delete(fixturePath);
			}
		}
		
		return new TestGroup("Code Fix Tools", [
			new("roslyn_preview/apply_code_fix: RMCP001 IntPtr → nint",
				() => RunApplyNintFix())
		]);
	}
}
