using System.Text.Json.Nodes;

static class FindUnusedTests
{
	internal static TestGroup Build(TestContext ctx)
	{
		var fixturePath = Path.Combine(ctx.TargetPath, "0_FindUnusedFixture_.cs");
		var generatedFixturePath = Path.Combine(ctx.TargetPath, "0_FindUnusedFixture_.generated.cs");
		var generatedSuffixPath = Path.Combine(ctx.TargetPath, "0_FindUnusedSuffixFixture.g.cs");
		var designerSuffixPath = Path.Combine(ctx.TargetPath, "0_FindUnusedDesignerFixture.designer.cs");
		
		File.WriteAllText(fixturePath, """
		using System.Runtime.CompilerServices;
		
		[assembly: InternalsVisibleTo("_FindUnusedFriendAssembly_")]
		
		namespace RoslynMcp;
		
		public sealed class _FindUnusedAnchor_
		{
			public void Touch()
			{
				_ = typeof(_FindUnusedInternalFixture_);
				_ = typeof(_FindUnusedEffectivelyInternalFixture_);
				_ = typeof(_FindUnusedAttributedFixture_);
				_ = typeof(_FindUnusedPartialGeneratedFixture_);
				_ = typeof(_FindUnusedPartialMethodFixture_);
				_ = typeof(_FindUnusedInterfaceImplementation_);
				_ = typeof(_FindUnusedOwnAttributeFixture_);
				_ = typeof(_FindUnusedInheritanceFixture_);
				_ = typeof(_FindUnusedMainFixture_);
				_ = typeof(_FindUnusedEnumFixture_);
				_ = typeof(_FindUnusedPropertyUsageFixture_);
				_ = typeof(_FindUnusedEventUsageFixture_);
				_ = typeof(_FindUnusedPartialAttributedFixture_);
			}
		}
		
		internal sealed class _FindUnusedInternalFixture_
		{
			internal _FindUnusedInternalFixture_()
			{
			}
			
			private void _FindUnusedPrivateMethod_()
			{
			}
			
			internal void _FindUnusedInternalMethod_()
			{
			}
			
			protected void _FindUnusedProtectedMethod_()
			{
			}
		}
		
		internal sealed class _FindUnusedUnreferencedContainer_
		{
			private void _FindUnusedChildSuppressedByUnusedType_()
			{
			}
		}
		
		internal sealed class _FindUnusedEffectivelyInternalFixture_
		{
			public void _FindUnusedPublicInsideInternal_()
			{
			}
		}
		
		[System.Obsolete]
		internal sealed class _FindUnusedAttributedFixture_
		{
			internal string _FindUnusedMemberInsideAttributedType_ { get; set; } = string.Empty;
		}
		
		internal sealed class _FindUnusedOwnAttributeFixture_
		{
			[System.Obsolete]
			internal void _FindUnusedOwnAttributedMethod_()
			{
			}
		}
		
		internal partial class _FindUnusedPartialGeneratedFixture_
		{
			internal void _FindUnusedMemberInsideGeneratedPartial_()
			{
			}
		}
		
		internal partial class _FindUnusedPartialMethodFixture_
		{
			partial void _FindUnusedPartialMethod_();
		}
		
		internal partial class _FindUnusedPartialMethodFixture_
		{
			partial void _FindUnusedPartialMethod_()
			{
			}
		}
		
		[System.Obsolete]
		internal partial class _FindUnusedPartialAttributedFixture_
		{
		}
		
		internal partial class _FindUnusedPartialAttributedFixture_
		{
			internal void _FindUnusedMemberInsideAttributedPartial_()
			{
			}
		}
		
		internal interface _FindUnusedInterface_
		{
			void _FindUnusedInterfaceMethod_();
		}
		
		internal sealed class _FindUnusedInterfaceImplementation_ : _FindUnusedInterface_
		{
			public void _FindUnusedInterfaceMethod_()
			{
			}
		}
		
		internal abstract class _FindUnusedInheritanceFixture_
		{
			internal virtual void _FindUnusedVirtualMethod_()
			{
			}
			
			internal abstract void _FindUnusedAbstractMethod_();
		}
		
		internal sealed class _FindUnusedOverrideFixture_ : _FindUnusedInheritanceFixture_
		{
			internal override void _FindUnusedVirtualMethod_()
			{
			}
			
			internal override void _FindUnusedAbstractMethod_()
			{
			}
		}
		
		internal sealed class _FindUnusedMainFixture_
		{
			private static int Main(int value)
				=> value;
		}
		
		internal enum _FindUnusedEnumFixture_
		{
			_FindUnusedEnumMember_
		}
		
		internal sealed class _FindUnusedPropertyUsageFixture_
		{
			private string _FindUnusedGetterReferencedProperty_ { get; set; } = string.Empty;
			private string _FindUnusedSetterReferencedProperty_ { get; set; } = string.Empty;
			
			private void Read()
			{
				_ = _FindUnusedGetterReferencedProperty_;
			}
			
			private void Write()
			{
				_FindUnusedSetterReferencedProperty_ = string.Empty;
			}
		}
		
		internal sealed class _FindUnusedEventUsageFixture_
		{
			private event System.Action? _FindUnusedSubscribedEvent_;
			
			private void Subscribe()
			{
				_FindUnusedSubscribedEvent_ += Handler;
			}
			
			private void Handler()
			{
			}
		}
		""");
		
		File.WriteAllText(generatedFixturePath, """
		// <auto-generated />
		namespace RoslynMcp;
		
		internal partial class _FindUnusedPartialGeneratedFixture_
		{
		}
		""");
		
		File.WriteAllText(generatedSuffixPath, """
		namespace RoslynMcp;
		
		internal sealed class _FindUnusedGeneratedSuffixFixture_
		{
			internal void _FindUnusedGeneratedSuffixMethod_()
			{
			}
		}
		""");
		
		File.WriteAllText(designerSuffixPath, """
		namespace RoslynMcp;
		
		internal sealed class _FindUnusedDesignerSuffixFixture_
		{
			internal void _FindUnusedDesignerSuffixMethod_()
			{
			}
		}
		""");
		
		var tests = new List<TestCase> {
			
			new("roslyn_find_unused: reports conservative candidates with confidence metadata",
				() => ctx.RunTestAsync(
					"roslyn_find_unused",
					new { projectPath = ctx.TargetPath, take = 200 },
					data => {
						var unused = data?["unused"]?.AsArray();
						
						return unused is not null
							&& HasEntry(unused, "_FindUnusedPrivateMethod_", "private", "high")
							&& HasEntry(unused, "_FindUnusedInternalMethod_", "internal", "medium", "friend assemblies")
							&& HasEntry(unused, "_FindUnusedInternalFixture_()", "internal", "medium")
							&& HasEntry(unused, "_FindUnusedPublicInsideInternal_", "public", "medium")
							&& HasEntry(unused, "_FindUnusedUnreferencedContainer_", "internal", "medium");
					})),
			
			new("roslyn_find_unused: skips reflection, generated, partial, protected, and interface-risky symbols",
				() => ctx.RunTestAsync(
					"roslyn_find_unused",
					new { projectPath = ctx.TargetPath, take = 200 },
					data => {
						var unused = data?["unused"]?.AsArray();
						
						return unused is not null
							&& !HasEntry(unused, "_FindUnusedProtectedMethod_")
							&& !HasEntry(unused, "_FindUnusedMemberInsideAttributedType_")
							&& !HasEntry(unused, "_FindUnusedMemberInsideGeneratedPartial_")
							&& !HasEntry(unused, "_FindUnusedPartialMethod_")
							&& !HasEntry(unused, "_FindUnusedInterfaceMethod_")
							&& !HasEntry(unused, "_FindUnusedOwnAttributedMethod_")
							&& !HasEntry(unused, "_FindUnusedGeneratedSuffixMethod_")
							&& !HasEntry(unused, "_FindUnusedDesignerSuffixMethod_")
							&& !HasEntry(unused, "_FindUnusedVirtualMethod_")
							&& !HasEntry(unused, "_FindUnusedAbstractMethod_")
							&& !HasEntry(unused, "Main(int)")
							&& !HasEntry(unused, "_FindUnusedEnumMember_")
							&& !HasEntry(unused, "_FindUnusedChildSuppressedByUnusedType_")
							&& !HasEntry(unused, "_FindUnusedGetterReferencedProperty_")
							&& !HasEntry(unused, "_FindUnusedSetterReferencedProperty_")
							&& !HasEntry(unused, "_FindUnusedSubscribedEvent_")
							&& !HasEntry(unused, "_FindUnusedMemberInsideAttributedPartial_");
					})),
		};
		
		return new TestGroup($"Unused Symbol Analysis ({tests.Count} tests)", tests, Teardown: () =>
		{
			try { File.Delete(fixturePath); } catch { }
			try { File.Delete(generatedFixturePath); } catch { }
			try { File.Delete(generatedSuffixPath); } catch { }
			try { File.Delete(designerSuffixPath); } catch { }
			
			return Task.CompletedTask;
		});
	}
	
	private static bool HasEntry(JsonArray unused, string nameFragment, string? accessibility = null, string? confidence = null, string? reasonFragment = null)
	{
		return unused.Any(entry => {
			
			var name = entry?["name"]?.GetValue<string>();
			var reason = entry?["reason"]?.GetValue<string>();
			
			if(name?.Contains(nameFragment, StringComparison.Ordinal) != true)
				return false;
			
			if(accessibility is not null && entry?["accessibility"]?.GetValue<string>() != accessibility)
				return false;
			
			if(confidence is not null && entry?["confidence"]?.GetValue<string>() != confidence)
				return false;
			
			if(reasonFragment is not null && reason?.Contains(reasonFragment, StringComparison.OrdinalIgnoreCase) != true)
				return false;
			
			return reason is { Length: > 0 };
		});
	}
}
