using System.Diagnostics;
using System.Text.Json.Nodes;

internal static class RefactoringTests
{
	internal static TestGroup Build(TestContext ctx)
	{
		
		// Calls a tool and returns (no-protocol-error, parsed JSON data, raw content text).
		async Task<(bool ok, JsonNode? data, string text)> Call(string tool, object args)
		{
			
			await ctx.SendAsync(new { jsonrpc = "2.0", id = ctx.NextId(), method = "tools/call",
				@params = new { name = tool, arguments = args } });
			
			var resp = await ctx.ReceiveAsync();
			var text = resp?["result"]?["content"]?[0]?["text"]?.GetValue<string>() ?? string.Empty;
			
			JsonNode? data = null;
			
			try { data = JsonNode.Parse(text); }
			catch { }
			
			return (resp?["error"] is null && text.Length > 0, data, text);
		}
		
		// The rename fixtures live in a temp MSBuild project (#274) — apply_rename's file-rename
		// bookkeeping needs MSBuild — and are written before the first tool call, so the initial load
		// includes them. That replaces the old 600 ms waits on the FSW debounce, and nothing is
		// written into src/RoslynMcp any more.
		var fx = TestFixtures.NewMsBuildProject("Rename");
		
		// Class name intentionally differs from file stem — RenameFile only triggers when they match.
		fx.Write("_RenameFixture_.cs", """
			// AUTO-GENERATED by TestHarness — safe to delete.
			namespace RoslynMcp
			;
			
			class _RenameFixtureTarget_
			{
				public void Placeholder() { }
			}
			""");
		
		// Class name matches file stem → apply_rename renames the file as well.
		fx.Write("_FileRenameFixture_.cs", """
			// AUTO-GENERATED by TestHarness — safe to delete.
			namespace RoslynMcp
			;
			
			class _FileRenameFixture_
			{
				public void Placeholder() { }
			}
			""");
		
		// 1. Full apply: preview → apply → verify files_written >= 1.
		async Task<(bool pass, string msg)> RunApplySuccess()
		{
			
			var sw = Stopwatch.StartNew();
			
			var (_, pvData, _) = await Call("roslyn_preview_rename", new {
				
				symbolName  = "_RenameFixtureTarget_",
				newName     = "_RenameFixtureRenamed_",
				projectPath = fx.Csproj
			});
			
			var token = pvData?["token"]?.GetValue<string>();
			
			if(token is null)
				
				return (false, $"FAIL  (no preview token — class not found in workspace?) [{sw.ElapsedMilliseconds}ms]");
			
			var (_, apData, _) = await Call("roslyn_apply_rename", new {
				token, approval = "y", projectPath = fx.Csproj
			});
			
			var error        = apData?["error"]?.GetValue<string>();
			var filesWritten = apData?["filesWritten"]?.GetValue<int>();
			var pass         = error is null && filesWritten >= 1;
			
			return (pass,
				pass
					? $"PASS  [{sw.ElapsedMilliseconds}ms]"
					: $"FAIL  (error: {error ?? "null"}, files_written: {filesWritten}) [{sw.ElapsedMilliseconds}ms]"
			);
		}
		
		// 6. File rename: class name matches file stem → file renamed automatically.
		async Task<(bool pass, string msg)> RunFileRename()
		{
			
			var renamedPath = fx.PathOf("_FileRenameRenamed_.cs");
			var sw = Stopwatch.StartNew();
			
			var (_, pvData, _) = await Call("roslyn_preview_rename", new {
				
				symbolName  = "_FileRenameFixture_",
				newName     = "_FileRenameRenamed_",
				projectPath = fx.Csproj
			});
			
			var token = pvData?["token"]?.GetValue<string>();
			
			if(token is null)
				
				return (false, $"FAIL  (no preview token — class not found in workspace?) [{sw.ElapsedMilliseconds}ms]");
			
			var (_, apData, _) = await Call("roslyn_apply_rename", new {
				token, approval = "y", projectPath = fx.Csproj
			});
			
			var error        = apData?["error"]?.GetValue<string>();
			var filesRenamed = apData?["filesRenamed"]?.GetValue<int>();
			var pass         = error is null && filesRenamed >= 1 && File.Exists(renamedPath);
			
			return (pass,
				pass
					? $"PASS  [{sw.ElapsedMilliseconds}ms]"
					: $"FAIL  (error: {error ?? "null"}, files_renamed: {filesRenamed}, renamed file exists: {File.Exists(renamedPath)}) [{sw.ElapsedMilliseconds}ms]"
			);
		}
		
		var tests = new List<TestCase> {
			
			// ── preview_rename ──────────────────────────────────────────────────────
			
			new("roslyn_preview_rename: generate diff for renaming a symbol",
				() => ctx.RunTestAsync(
					"roslyn_preview_rename",
					new { symbolName = "NormalizePath", newName = "NormalizePath2", containingType = "RoslynMcpTool", projectPath = ctx.TargetPath },
					data => data?["token"] is not null)),
			
			// The harness starts the server without --elicit, so ambiguity must take the default
			// agent-first path: a structured candidates failure with the machine-usable retry
			// fields — never a silent first match, never an interactive prompt. GetSolution is
			// naturally ambiguous in the target (WorkspaceManager, WorkspaceInstance, WorkspaceResolver).
			new("roslyn_preview_rename: ambiguous name fails with candidate list",
				() => ctx.RunTestAsync(
					"roslyn_preview_rename",
					new { symbolName = "GetSolution", newName = "GetSolution2", projectPath = ctx.TargetPath },
					data => data?["token"] is null
						&& data?["error"]?.GetValue<string>()?.Contains("match 'GetSolution'") == true
						&& data?["candidates"]?.AsArray().Count >= 2
						&& data?["candidates"]?[0]?["containingType"]?.GetValue<string>() is not null
						&& data?["candidates"]?[0]?["filePath"]?.GetValue<string>() is not null
						&& data?["candidates"]?[0]?["line"]?.GetValue<int>() > 0)),
			
			// ── apply_rename ────────────────────────────────────────────────────────
			
			new("roslyn_apply_rename: rename class, verify file updated",
				() => RunApplySuccess()),
			
			new("roslyn_apply_rename: cancel with 'n' succeeds, writes nothing",
				async () => {
					
					var sw = Stopwatch.StartNew();
					var (_, pvData, _) = await Call("roslyn_preview_rename", new {
						
						symbolName = "NormalizePath", newName = "NormalizePath2",
						containingType = "RoslynMcpTool", projectPath = ctx.TargetPath
					});
					var token = pvData?["token"]?.GetValue<string>();
					
					if(token is null)
						
						return (false, $"FAIL  (no preview token) [{sw.ElapsedMilliseconds}ms]");
					
					var (_, apData, _) = await Call("roslyn_apply_rename", new {
						token, approval = "n", projectPath = ctx.TargetPath
					});
					var pass = apData?["error"] is null
						&& apData?["message"]?.GetValue<string>()?.Contains("No files were changed") == true;
					
					return (pass, pass ? $"PASS  [{sw.ElapsedMilliseconds}ms]" : $"FAIL  (error: {apData?["error"]}, message: {apData?["message"]}) [{sw.ElapsedMilliseconds}ms]");
				}),
			
			new("roslyn_apply_rename: invalid approval returns error",
				async () => {
					
					var sw = Stopwatch.StartNew();
					var (_, pvData, _) = await Call("roslyn_preview_rename", new {
						
						symbolName = "NormalizePath", newName = "NormalizePath2",
						containingType = "RoslynMcpTool", projectPath = ctx.TargetPath
					});
					var token = pvData?["token"]?.GetValue<string>();
					
					if(token is null)
						
						return (false, $"FAIL  (no preview token) [{sw.ElapsedMilliseconds}ms]");
					
					var (_, apData, _) = await Call("roslyn_apply_rename", new {
						token, approval = "xyz", projectPath = ctx.TargetPath
					});
					var pass = apData?["error"]?.GetValue<string>() == "invalid approval";
					
					return (pass, pass ? $"PASS  [{sw.ElapsedMilliseconds}ms]" : $"FAIL  (error: {apData?["error"]}) [{sw.ElapsedMilliseconds}ms]");
				}),
			
			new("roslyn_apply_rename: consumed token returns not found",
				async () => {
					
					var sw = Stopwatch.StartNew();
					var (_, pvData, _) = await Call("roslyn_preview_rename", new {
						
						symbolName = "NormalizePath", newName = "NormalizePath2",
						containingType = "RoslynMcpTool", projectPath = ctx.TargetPath
					});
					var token = pvData?["token"]?.GetValue<string>();
					
					if(token is null)
						
						return (false, $"FAIL  (no preview token) [{sw.ElapsedMilliseconds}ms]");
					
					// Reject token so it is consumed.
					await Call("roslyn_apply_rename", new { token, approval = "n", projectPath = ctx.TargetPath })
					;
					
					// Same token must now return "not found".
					var (_, apData, _) = await Call("roslyn_apply_rename", new {
						token, approval = "y", projectPath = ctx.TargetPath
					});
					var pass = apData?["error"]?.GetValue<string>() == "token not found";
					
					return (pass, pass ? $"PASS  [{sw.ElapsedMilliseconds}ms]" : $"FAIL  (error: {apData?["error"]}) [{sw.ElapsedMilliseconds}ms]");
				}),
			
			new("roslyn_apply_rename: unknown token returns error",
				() => ctx.RunTestAsync(
					"roslyn_apply_rename",
					new { token = "doesnotexist999", approval = "y", projectPath = ctx.TargetPath },
					data => data?["error"]?.GetValue<string>() == "token not found")),
			
			new("roslyn_apply_rename: file renamed when class name matches stem",
				() => RunFileRename()),
			
			// ── change_signature ────────────────────────────────────────────────────
			
			new("roslyn_change_signature: add parameter with default",
				() => ctx.RunTestAsync(
					"roslyn_change_signature",
					new {
						
						methodName     = "NormalizePath",
						containingType = "RoslynMcpTool",
						addParameters  = """[{"name":"toLower","type":"bool","defaultValue":"false"}]""",
						projectPath    = ctx.TargetPath
					},
					data => data?["token"] is not null
						&& data?["diff"]?.GetValue<string>().Contains("Obsolete") == true
						&& data?["parameters_added"]?.AsArray().Count == 1
						&& data?["deprecation_message"]?.GetValue<string>().Contains("NormalizePath") == true
						// Well-formedness of the synthesized code — regression guard for the
						// unformatted-SyntaxFactory bugs (returnFoo, comma/equals spacing) and
						// for the diff builder swallowing inserted lines as context.
						&& data?["diff"]?.GetValue<string>().Contains("bool toLower = false") == true
						&& data?["diff"]?.GetValue<string>().Contains("(string filePath) => NormalizePath(filePath, false);") == true)),
			
			new("roslyn_apply_signature_change: cancel with 'n' succeeds, writes nothing",
				async () => {
					
					var sw = Stopwatch.StartNew();
					var (_, pvData, _) = await Call("roslyn_change_signature", new {
						
						methodName     = "NormalizePath",
						containingType = "RoslynMcpTool",
						addParameters  = """[{"name":"toLower","type":"bool","defaultValue":"false"}]""",
						projectPath    = ctx.TargetPath
					});
					var token = pvData?["token"]?.GetValue<string>();
					
					if(token is null)
						
						return (false, $"FAIL  (no preview token) [{sw.ElapsedMilliseconds}ms]");
					
					var (_, apData, _) = await Call("roslyn_apply_signature_change", new {
						token, approval = "n", projectPath = ctx.TargetPath
					});
					var pass = apData?["error"] is null
						&& apData?["message"]?.GetValue<string>()?.Contains("No files were changed") == true;
					
					return (pass, pass ? $"PASS  [{sw.ElapsedMilliseconds}ms]" : $"FAIL  (error: {apData?["error"]}, message: {apData?["message"]}) [{sw.ElapsedMilliseconds}ms]");
				}),
			
			new("roslyn_change_signature: reject non-method symbol",
				() => ctx.RunTestAsync(
					"roslyn_change_signature",
					new {
						
						methodName    = "WorkspaceManager",
						addParameters = """[{"name":"x","type":"int"}]""",
						projectPath   = ctx.TargetPath
					},
					data => data?["error"]?.GetValue<string>().Contains("not a method") == true)),
			
			new("roslyn_change_signature: reject empty addParameters",
				() => ctx.RunTestAsync(
					"roslyn_change_signature",
					new {
						
						methodName     = "NormalizePath",
						containingType = "RoslynMcpTool",
						projectPath    = ctx.TargetPath
					},
					data => data?["error"]?.GetValue<string>().Contains("No parameters") == true)),
			
			new("roslyn_change_signature: reject invalid JSON",
				() => ctx.RunTestAsync(
					"roslyn_change_signature",
					new {
						
						methodName     = "NormalizePath",
						containingType = "RoslynMcpTool",
						addParameters  = "not valid json",
						projectPath    = ctx.TargetPath
					},
					data => data?["error"]?.GetValue<string>().Contains("parse") == true)),
			
			new("roslyn_change_signature: reject duplicate parameter name",
				() => ctx.RunTestAsync(
					"roslyn_change_signature",
					new {
						
						methodName     = "NormalizePath",
						containingType = "RoslynMcpTool",
						addParameters  = """[{"name":"filePath","type":"string"}]""",
						projectPath    = ctx.TargetPath
					},
					data => data?["error"]?.GetValue<string>().Contains("already exists") == true)),
		};
		
		return new TestGroup($"Refactoring Tools ({tests.Count} tests)", tests, Teardown: () =>
		{
			
			fx.Dispose();
			
			return Task.CompletedTask;
		});
	}
}
