using System.Text.Json.Nodes;

static class ValidationTests
{
	internal static async Task RunAsync(TestContext ctx, List<(bool pass, string message)> tests)
	{
		Console.WriteLine("\nValidation Tools (4 tests)");
		Console.WriteLine("─────────────────────────────────────────────────────────────");
		
		tests.Add(await ctx.RunTestAsync(
			"roslyn_get_diagnostics: check for compiler errors",
			"roslyn_get_diagnostics",
			new { projectPath = ctx.TargetPath },
			data => data?["errors"] is not null && data?["summary"] is not null
		));
		
		tests.Add(await ctx.RunTestAsync(
			"roslyn_build_project: smart Roslyn-first build",
			"roslyn_build_project",
			new { projectPath = ctx.TargetPath },
			data => data?["succeeded"] is not null && data?["source"] is not null
		));
		
		// Dynamic scratch file: create → call forceBuild → validate → delete.
		// This verifies ParseMSBuildDiagnostics correctly extracts structured errors
		// from real dotnet build output without needing a repub cycle.
		var scratchPath = Path.Combine(ctx.RepoRoot, "src", "RoslynMcp", "_BuildDiagnosticsTest_.cs");
		
		try {
			
			await File.WriteAllTextAsync(scratchPath, """
				// AUTO-GENERATED by TestHarness — safe to delete.
				namespace RoslynMcp;
				class _BuildDiagnosticsTest_
				{
					int _unusedField; // CS0169
					public int NotAllPathsReturn(bool cond)
					{ // CS0161
						if(cond) return 42;
					}
					public void Trigger()
					{
						var x = NonExistentVariable; // CS0103
						int unusedLocal; // CS0168
					}
				}
				""");
			
			tests.Add(await ctx.RunTestAsync(
				"roslyn_build_project: forceBuild reports CS errors from scratch file",
				"roslyn_build_project",
				new { projectPath = ctx.ServerProj, forceBuild = true },
				data => {
					
					var errors   = data?["errors"]?.AsArray();
					var warnings = data?["warnings"]?.AsArray();
					
					if(errors is null || warnings is null)
						return false;
					
					var errorCodes = errors.Select(e => e?["code"]?.GetValue<string>()).ToHashSet();
					var warnCodes  = warnings.Select(w => w?["code"]?.GetValue<string>()).ToHashSet();
					
					// CS0103 (undefined name) and CS0161 (not all paths return) must be in errors[].
					// CS0168 (unused local) and CS0169 (unused field) must be in warnings[].
					return errorCodes.Contains("CS0103")
						&& errorCodes.Contains("CS0161")
						&& warnCodes.Contains("CS0168")
						&& warnCodes.Contains("CS0169")
					;
				}
			));
			
			tests.Add(await ctx.RunTestAsync(
				"roslyn_build_project: forceBuild succeeded=false for scratch file",
				"roslyn_build_project",
				new { projectPath = ctx.ServerProj, forceBuild = true },
				data => data?["succeeded"]?.GetValue<bool>() == false
			));
			
			// The server project is multi-targeted (net8.0 + net10.0), so dotnet build
			// emits TFM-suffixed bracket contexts like [proj::TargetFramework=net10.0].
			// This test verifies ParseMSBuildDiagnostics populates target_frameworks on
			// at least one diagnostic item.
			tests.Add(await ctx.RunTestAsync(
				"roslyn_build_project: forceBuild populates target_frameworks on CS diagnostics",
				"roslyn_build_project",
				new { projectPath = ctx.ServerProj, forceBuild = true },
				data => {
					
					var errors   = data?["errors"]?.AsArray();
					var warnings = data?["warnings"]?.AsArray();
					
					if(errors is null || warnings is null)
						return false;
					
					return errors.Concat(warnings).Any(d =>
						d?["target_frameworks"]?.AsArray() is { } tfms
						&& tfms.Count > 0
						&& tfms.Any(t => t?.GetValue<string>()?.StartsWith("net") == true)
					);
				}
			));
		}
		finally {
			
			if(File.Exists(scratchPath))
				File.Delete(scratchPath);
		}
	}
}
