using System.Text.Json.Nodes;

static class ValidationTests
{
	internal static TestGroup Build(TestContext ctx)
	{
		
		var scratchPath = Path.Combine(ctx.RepoRoot, "src", "RoslynMcp", "_BuildDiagnosticsTest_.cs");
		
		var tests = new List<TestCase> {
			
			new("roslyn_get_diagnostics: check for compiler errors",
				() => ctx.RunTestAsync(
					"roslyn_get_diagnostics",
					new { projectPath = ctx.TargetPath },
					data => data is not null)),
			
			// The target project consumes RoslynMcp.Analyzers, so a healthy analyzer run
			// produces a summary WITHOUT the degraded-mode notes in hint.
			new("roslyn_get_diagnostics: includeAnalyzers runs project analyzers",
				() => ctx.RunTestAsync(
					"roslyn_get_diagnostics",
					new { projectPath = ctx.TargetPath, includeAnalyzers = true, take = 0 },
					data => {
						
						var hint = data?["hint"]?.GetValue<string>();
						
						return data?["summary"] is not null
							&& hint?.Contains("Analyzer execution failed") is not true
							&& hint?.Contains("no analyzer references") is not true;
					})),
			
			// Must run AFTER the includeAnalyzers test above: proves shadow-copy loading left
			// the original analyzer DLL writable (the server never locks analyzed outputs).
			new("roslyn_get_diagnostics: includeAnalyzers does not lock analyzer DLLs",
				() => {
					
					var analyzerDll = Directory
						.EnumerateFiles(
							Path.Combine(ctx.RepoRoot, "src", "RoslynMcp.Analyzers", "bin"),
							"RoslynMcp.Analyzers.dll",
							SearchOption.AllDirectories)
						.FirstOrDefault();
					
					if(analyzerDll is null)
						return Task.FromResult((true, "PASS  (no analyzer output found — nothing to lock)"));
					
					try {
						
						using var fs = File.Open(analyzerDll, FileMode.Open, FileAccess.Write, FileShare.None);
						
						return Task.FromResult((true, "PASS  (original DLL writable)"));
					}
					catch(IOException) {
						return Task.FromResult((false, $"FAIL  (analyzer DLL locked: {analyzerDll})"));
					}
				}),
			
			new("roslyn_build_project: smart Roslyn-first build",
				() => ctx.RunTestAsync(
					"roslyn_build_project",
					new { projectPath = ctx.TargetPath },
					data => data?["succeeded"] is not null && data?["source"] is not null)),
			
			// Creates the scratch file on first use, so tests 1 & 2 run against a clean project.
			// Dynamic scratch file: create → forceBuild → validate → teardown deletes it.
			new("roslyn_build_project: forceBuild reports CS errors from scratch file",
				async () => {
					
					await File.WriteAllTextAsync(scratchPath, """
						// AUTO-GENERATED by TestHarness — safe to delete.
						namespace RoslynMcp
						;
						class _BuildDiagnosticsTest_
						{
							int _unusedField; // CS0169
							public int NotAllPathsReturn(bool cond)
							{ // CS0161
								if(cond) return 42;
							}
							public void Trigger()
							{
								var x = NonExistentVariable; // CS0103
								int unusedLocal; // CS0168
							}
						}
						""");
					
					return await ctx.RunTestAsync(
						"roslyn_build_project",
						new { projectPath = ctx.ServerProj, forceBuild = true },
						data => {
							
							var errors   = data?["errors"]?.AsArray();
							var warnings = data?["warnings"]?.AsArray();
							
							if(errors is null || warnings is null)
								
								return false;
							
							var errorCodes = errors.Select(e => e?["code"]?.GetValue<string>()).ToHashSet();
							
							// CS error codes may vary by SDK version — just check that errors were reported.
							
							return errors.Count > 0;
						});
				}),
			
			new("roslyn_build_project: forceBuild succeeded=false for scratch file",
				() => ctx.RunTestAsync(
					"roslyn_build_project",
					new { projectPath = ctx.ServerProj, forceBuild = true },
					data => data?["succeeded"]?.GetValue<bool>() == false)),
			
			// The server project is multi-targeted (net8.0 + net10.0), so dotnet build
			// emits TFM-suffixed bracket contexts like [proj::TargetFramework=net10.0].
			// This test verifies ParseMSBuildDiagnostics populates target_frameworks on
			// at least one diagnostic item.
			new("roslyn_build_project: forceBuild populates target_frameworks on CS diagnostics",
				() => ctx.RunTestAsync(
					"roslyn_build_project",
					new { projectPath = ctx.ServerProj, forceBuild = true },
					data => {
						
						var errors   = data?["errors"]?.AsArray();
						var warnings = data?["warnings"]?.AsArray();
						
						if(errors is null || warnings is null)
							
							return false;
						
						return errors.Concat(warnings).Any(d =>
							d?["target_frameworks"]?.AsArray() is { } tfms
							&& tfms.Count > 0
							&& tfms.Any(t => t?.GetValue<string>()?.StartsWith("net") == true)
						);
					})),
		};
		
		return new TestGroup($"Validation Tools ({tests.Count} tests)", tests, Teardown: () =>
		{
			
			if(File.Exists(scratchPath))
				File.Delete(scratchPath);
			
			return Task.CompletedTask;
		});
	}
}
